### PR TITLE
Update all-in-one-template in accordance with k8s 1.16

### PR DESCRIPTION
**Pull request by fredrikssongustav**
## Which problem is this PR solving?
Adds the changes mentioned in the https://github.com/jaegertracing/jaeger-kubernetes/issues/120 due to the related PR's delay

## Short description of the changes
Refactoring of the `jaeger-all-in-one-template.yml` according to changed defined in [ changelog k8s 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

### CODE REVIEW

**Comment by jpkrohling** [comment]
I wasn't sure if the failure was an intermittent one, so, I restarted the build.

**Comment by fredrikssongustav** [comment]
> I wasn't sure if the failure was an intermittent one, so, I restarted the build.

Build seems to fail. I am unable to see any actable logs–can you see what's broken? Do tests maybe assume an older k8s version?

**Comment by jpkrohling** [comment]
That might indeed be the case:

https://github.com/jaegertracing/jaeger-kubernetes/blob/bcca10c297b38c01d9d7c554172572ffa11944ce/travis/install-start-minikube.sh#L16-L17

I remember @pavolloffay (or @kevinearls) saying that any newer version of minikube would require more memory than Travis can handle, but perhaps it's worth a try?

**Comment by kevinearls** [comment]
@jpkrohling it might have been @pavolloffay, but I don't remember anything like this.

**Comment by pavolloffay** [comment]
> I remember @pavolloffay (or @kevinearls) saying that any newer version of minikube would require more memory than Travis can handle, but perhaps it's worth a try?

That wasn't me :). The CI for cassandra and ES passed so it might be something related to the template itself if it failed after restart.


That said. I would like to see this repository being deprecated and we should rather provide all-in-one template as part of the operator repo https://github.com/jaegertracing/jaeger-operator/issues/375.

**Comment by fredrikssongustav** [comment]
> That wasn't me :). The CI for cassandra and ES passed so it might be something related to the template itself if it failed after restart.
> 
> That said. I would like to see this repository being deprecated and we should rather provide all-in-one template as part of the operator repo [jaegertracing/jaeger-operator#375](https://github.com/jaegertracing/jaeger-operator/issues/375).

Is that something that is planned to happen in the near future? Elsewise, it might make sense to update this repo to suit later versions of k8s? :-)

**Comment by jpkrohling** [comment]
> That said. I would like to see this repository being deprecated and we should rather provide all-in-one template as part of the operator repo jaegertracing/jaeger-operator#375.

Agree with the deprecation notice, but we should keep the template here, possibly linked from the readme. If we store it inside the operator, it might confuse users.

@fredrikssongustav if you can get the CI to work (any CI, doesn't have to be Travis), we can happily merge your PR.

**Comment by fredrikssongustav** [comment]
> if you can get the CI to work (any CI, doesn't have to be Travis), we can happily merge your PR.

@jpkrohling, I am not too familiar with Travis logs. Any ideas what I need to adjust in order to make it work?

**Comment by jpkrohling** [comment]
You can see the logs here: https://travis-ci.org/jaegertracing/jaeger-kubernetes/jobs/611776862#L1214

Below is the relevant excerpt: 
```
310.80s$ travis/install-start-minikube.sh && export PATH=`pwd`:${PATH}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 46.3M  100 46.3M    0     0   146M      0 --:--:-- --:--:-- --:--:--  146M

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100 44.5M  100 44.5M    0     0  26.9M      0  0:00:01  0:00:01 --:--:-- 26.9M

* minikube v1.5.2 on Ubuntu 14.04

  - KUBECONFIG=/home/travis/.kube/config

  - MINIKUBE_WANTREPORTERRORPROMPT=false

  - MINIKUBE_WANTUPDATENOTIFICATION=false

  - MINIKUBE_HOME=/home/travis

! 'none' driver reported a possible issue: exec: "systemctl": executable file not found in $PATH

* Suggestion: Use a systemd based Linux distribution

* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

* Running on localhost (CPUs=2, Memory=7479MB, Disk=70522MB) ...

* OS release is Ubuntu 14.04.5 LTS

* 

X Failed to enable container runtime: enable docker.: command failed: sudo systemctl start docker

stdout: 

stderr: sudo: systemctl: command not found

: exit status 1

* 

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

  - https://github.com/kubernetes/minikube/issues/new/choose

0.06s$ kubectl get all --all-namespaces

The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by pavolloffay** [comment]
Now your build is failing on 

> [WARNING] Unknown file extension: /home/travis/build/jaegertracing/jaeger-kubernetes/minikube
> [WARNING] Unknown file extension: /home/travis/build/jaegertracing/jaeger-kubernetes/kubectl
> [WARNING] Missing header in: /home/travis/build/jaegertracing/jaeger-kubernetes/travis/install-st

I recommend runing the build locally with minikube and see whether it passes

**Comment by fredrikssongustav** [comment]
> I recommend runing the build locally with minikube and see whether it passes

Yeah I started debugging it, will get back to it asap! :-)

**Pull request closed without merging**
