### PR TITLE
Readme IDE test, copy template

### PR DESCRIPTION
**Pull request by pavolloffay**
@jpkrohling could you please review?

### CODE REVIEW

**Comment by pavolloffay** [comment]
It does so, but when you execute the test from IDE it doesn't go through maven.

**Comment by pavolloffay** [comment]
Copying templates were in profile I moved it to the main `<build>` and It works fine with Intellij IDEA.

**Comment by pavolloffay** [comment]
@jpkrohling thanks! So it seems that idea executes pom.xml in some way. I'm not sure whether it works in different IDEs. cc @objectiser :)

**Comment by objectiser** [comment]
@pavolloffay No Eclipse needs the file to be manually copied.

**Comment by pavolloffay** [comment]
@objectiser thanks for testing it. I have added a comment to the readme.

**Pull request merged**
