### PR TITLE
jaeger-cassandra-schema-job: unset activeDeadlineSeconds

### PR DESCRIPTION
**Pull request by jgehrcke**
Please also see commit message.

## Which problem is this PR solving?
- Context: https://github.com/jaegertracing/jaeger-kubernetes/issues/32
- `jaeger-cassandra-schema-job` can transition into a permanent failure state that requires human intervention, although the underlying problem is most often a transient one.  

## Short description of the changes
- Do not apply a deadline, simply keep trying to create the schema until it succeeds.
- This is a follow-up patch after my comment here: https://github.com/jaegertracing/jaeger-kubernetes/issues/32#issuecomment-573032045

Feedback welcome. What do you think? Any negative implications in this that we do not want to have?

### CODE REVIEW

**Comment by jpkrohling** [comment]
Waiting for an agreement on #32. If we decide to indeed remove this, we might want to remove it from the jaeger-operator as well. 

https://github.com/jaegertracing/jaeger-operator/blob/5999ea6f1057cc63d30888272e9f101a697da8f6/pkg/storage/cassandra_dependencies.go#L60-L77

**Comment by jpkrohling** [comment]
By the way: Travis failed with `[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project jaegertracing-kubernetes-production: Some files do not have the expected license header -> [Help 1]`. 

You can probably fix this by running `mvn license:format`

**Comment by jgehrcke** [comment]
I have updated the branch after discussion in https://github.com/jaegertracing/jaeger-kubernetes/issues/32.

**Comment by jpkrohling** [comment]
> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project jaegertracing-kubernetes-production: Some files do not have the expected license header -> [Help 1]

You might need to run `mvn license:format` and update the PR.

**Comment by jgehrcke** [comment]
> [WARNING] Missing header in: /home/travis/build/jaegertracing/jaeger-kubernetes/production/cassandra.yml

There is a header: https://github.com/jaegertracing/jaeger-kubernetes/blob/bcca10c297b38c01d9d7c554172572ffa11944ce/production/cassandra.yml#L2

Can you maybe simply point me to the correct header so that I can commit that instead of running `mvn license:format`? :) Is it just about the year, 2020?

**Comment by jpkrohling** [comment]
Yes, it's likely just the year :-)

**Comment by jgehrcke** [comment]
I should say that this change is not tested! After that much discussion and documentation reading we can however be quite confident that this works as intended.

**Comment by jgehrcke** [comment]
@jpkrohling what do you think about the current shape of the patch?

If we are happy with this method I am happy to patch https://github.com/jaegertracing/jaeger-operator/blob/0a8c2aac499437daf352ba8911797c6dac7b5fd2/pkg/storage/cassandra_dependencies.go, too.

**Comment by jpkrohling** [comment]
I think this looks good and ready to be merged.

**Comment by jgehrcke** [comment]
Thanks!

**Pull request merged**
