### PR TITLE
Enable zipkin by flag no ENV prop

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
Nothing specifically, just to unify binary configuration. It was using flags and env prop.

**Comment by objectiser** [comment]
But the env property can be overridden, whereas this change hardcodes the port.

**Comment by pavolloffay** [comment]
@objectiser how does it work? Does it have to be changed in pod or service? Then you restart the pod and  it will use the new port? 

I think it's better to change it on `zipkin-service` pods can use arbitrary ports.

**Comment by pavolloffay** [comment]
@objectiser NP, but I would like to still know if the change of env var is propagated to pod restarts and where it has to be changed. cc @jpkrohling ^^^^


It seems that our tests are again failing but on different error. I will have a look at it.

**Comment by jpkrohling** [comment]
> Does it have to be changed in pod or service?

On pure Kubernetes, yes, it has to be changed on the pod. But there might be solutions out there providing a more intuitive UI for managing env vars. 

> Then you restart the pod and it will use the new port?

Yes, but Kubernetes itself would schedule a restart according to the pod's strategy. 

> I think it's better to change it on zipkin-service pods can use arbitrary ports.

I have no strong opinions about this. Just make sure to add an entry "somewhere" (readme?) that documents this as the recommended approach.

**Comment by pavolloffay** [comment]
> I have no strong opinions about this. Just make sure to add an entry "somewhere" (readme?) that documents this as the recommended approach.

Isn't this k8s best practice?

**Comment by jpkrohling** [comment]
Just to document what we talked in private: for the moment, we'll keep the current behavior (without this PR). Once the config map support is merged, we'll see if this is needed. The main reason is that it's easier to change env vars than the entry command for the container. Besides, when using a config file, the command line flag takes precedence, so, changes to the external config file will not have any effect.

**Pull request closed without merging**
