### PR TITLE
Use recommended labels

### PR DESCRIPTION
**Pull request by naseemkullah**
## Which problem is this PR solving?
Not a problem per se, but using standards helps everybody in the long run.

## Short description of the changes
Using recommended labels as per https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

If approved I will go on to make a similar change to the incubating helm chart.

PS Also updated some images.

TIA

### CODE REVIEW

**Comment by jpkrohling** [comment]
We had a very similar PR for the Operator: https://github.com/jaegertracing/jaeger-operator/pull/172

It would be nice to be consistent here, especially regarding backwards compatibility.

**Comment by naseemkullah** [comment]
Thanks @jpkrohling , I've added back the original `app` label for backwards compatibility. Please let me know if this will suffice.

**Comment by naseemkullah** [comment]
Great, thanks @jpkrohling !

**Comment by naseemkullah** [comment]
bump

**Comment by jpkrohling** [comment]
Thanks for reminding me and thanks for your contribution!

**Comment by naseemkullah** [comment]
My pleasure!

**Pull request merged**
