### PR TITLE
Do not merge!

### PR DESCRIPTION
**Pull request by pavolloffay**
Shows how to fix CI for #75 

```diff
diff --git a/jaeger-production-template.yml b/jaeger-production-template.yml
index a6d1ea6..ec620ae 100644
--- a/jaeger-production-template.yml
+++ b/jaeger-production-template.yml
@@ -15,7 +15,7 @@
 apiVersion: v1
 kind: List
 items:
-- apiVersion: apps/v1
+- apiVersion: extensions/v1beta1
   kind: Deployment
   metadata:
     name: jaeger-collector
@@ -103,7 +103,7 @@ items:
     selector:
       jaeger-infra: collector-pod
     type: ClusterIP
-- apiVersion: apps/v1
+- apiVersion: extensions/v1beta1
   kind: Deployment
   metadata:
     name: jaeger-query
@@ -169,7 +169,7 @@ items:
     selector:
       jaeger-infra: query-pod
     type: LoadBalancer
-- apiVersion: apps/v1
+- apiVersion: extensions/v1beta1
   kind: DaemonSet
   metadata:
     name: jaeger-agent
```

### CODE REVIEW

**Comment by jpkrohling** [comment]
Does this mean that the testing framework is outdated? "apps/v1" is what the documentation for `DaemonSet` uses:
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by pavolloffay** [comment]
Probably, I don't know how recent is this change. will our resources work on older k8s version if we use `apps/v1` ?

**Comment by pavolloffay** [comment]
Now the CI fails because of recent change in minikube release https://github.com/kubernetes/minikube/issues/2629

**Comment by pavolloffay** [comment]
CI passed

**Pull request closed without merging**
