### PR TITLE
Fixed: set --es.num-shards to 1. By default jaeger st this value to 5…

### PR DESCRIPTION
**Pull request by Dogild**
…, this could create some issues since we have only one node of elasticseearch here

Signed-off-by: Alexandre Wilhelm <contact.dogild@gmail.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
I think we should rather set the number of replicas greater than 1. We do the same for C*.

**Comment by Dogild** [comment]
Not sure if it works out of the box for elastic search though. It needs some test first

**Comment by pavolloffay** [comment]
@Dogild I have created https://github.com/jaegertracing/jaeger-kubernetes/pull/46 which deploys two instances. It seems that it works unless there is something not obvious.

**Comment by pavolloffay** [comment]
It seems that #46 does not work properly. Data are not propagated to all nodes. We will revert to one replica in #50. 


@Dogild could you  please provide some references why 5 shards can cause problem with one ES node? 

cc @yurishkuro @black-adder @mh-park

**Comment by Dogild** [comment]
@pavolloffay we experienced missing data and lost of connectivity between es and the the query node

**Comment by pavolloffay** [comment]
From what I have been told single ES node can still use multiple shards, It can even be more performant if it has enough resources compared to single shard node.

**Comment by pavolloffay** [comment]
@Dogild thanks for the PR. I will close it for now, based on my research it's valid to use more than 1 shard on a single node ES. It can lead to a better performance. 

Please open an issue if you run into any problems with this configuration.

**Comment by pavolloffay** [comment]
I think the issue is with replicas. Our template should use zero replicas.

**Pull request closed without merging**
